# Change these first
owner: anna-colenso
repo: test-status-monitor
user-agent: anna-colenso
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  baseUrl: /test-status-monitor
  name: Your Status Website
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
