# Change these first
owner: anna-colenso
repo: test-status-monitor
user-agent: anna-colenso
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Test Broken Site
    url: https://thissitedoesnotexist2.koj.co

status-website:
  baseUrl: /test-status-monitor
  name: Your Status Website
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
